//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Héros
    {
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string Spécialité { get; set; }
        public string Classe_héro { get; set; }
        public Nullable<int> Niveau { get; set; }
        public Nullable<int> Puissance { get; set; }
        public Nullable<int> Réussite { get; set; }
        public string Réputation { get; set; }
        public int Héro_id { get; set; }
    }
}
